

const actionTypes = {
    FETCH_REQUEST: "FETCH_REQUEST",
    FETCH_SUCCSES: "FETCH_SUCCSES",
    FETCH_ERROR: "FETCH_ERROR",
    LOCATION_REQUEST: "LOCATION_REQUEST",
    LOCATION_SUCCSES: "LOCATION_SUCCSES",
    LOCATION_ERROR: "LOCATION_ERROR",
}

export default actionTypes;